### ISSUE TITLE
Social security contributions - staty kde nam nesedia data + paid leave 

### ISSUE THREAD

**Issue by Michaela142** [Michaela142/social-#1]
### Estonsko

Tu dali do obidvoch suborov 33% ze to plati aj zamestanec aj zamestnavatel, ale na Tradingeconomics je opat iny udaj, tak aby sme vedeli ktory zapisat, lebo nedava mi to zmysel aby obidvaja platili 33%

_TradingEconomics_
<img width="440" alt="Screenshot 2023-07-04 at 12 59 46" src="https://github.com/Michaela142/social-/assets/129953816/6eda0484-e8a5-4121-8a47-a0266d916c1e">

_WPC_
<img width="646" alt="Screenshot 2023-07-04 at 12 59 54" src="https://github.com/Michaela142/social-/assets/129953816/e06e66c9-e1e4-4f9f-a440-f0752b6c6a99">

Oficialny web Estonska
<img width="684" alt="Screenshot 2023-07-06 at 10 27 49" src="https://github.com/Michaela142/social-/assets/129953816/0b169a81-2047-4b54-b4ff-7f3e3bab1997">

https://www.eesti.ee/en/doing-business/occupational-environment-and-personnel/health-insurance-and-taxes
a
https://boundlesshq.com/guides/estonia/taxes/ (odtial to vychadza tak ako to je v tradingeconomics cize 33% plati zamestnavatel a 3.6% zamestnanec)

**Comment by Michaela142** [comment]
Tinka staty

**Comment by Kristinamal** [comment]
### Holandsko:
- Udaje na Pwc uvedene v mene, nie %. Na Deloitte neuvedene ziadne ciselne udaje, Trading economics uvadza %

Pwc a Deloitte:
![image](https://github.com/Michaela142/social-/assets/129856961/cc2bde5e-e690-462f-b714-63c399bd14fd)
https://taxsummaries.pwc.com/netherlands/individual/other-taxes

![image](https://github.com/Michaela142/social-/assets/129856961/c9961a69-5933-4b77-a3c7-ef466deab1b1)
https://www2.deloitte.com/content/dam/Deloitte/global/Documents/Tax/dttl-tax-netherlandshighlights-2023.pdf

Trading economics:
![image](https://github.com/Michaela142/social-/assets/129856961/f947ea17-4aa4-4f84-8aeb-b55633a14b3a)
https://tradingeconomics.com/netherlands/indicators

_______________________________________________________________________________________________________________________________________

### Srbsko:
- Cisla navzajom sedia na Deloitte a Pwc ale mierne sa odlisuju od Trading Economics (iba 1%, posledny update je z 2023)

Deloitte a Pwc:
![image](https://github.com/Michaela142/social-/assets/129856961/ac64b351-107d-4607-a34c-d18416b7094f)
https://taxsummaries.pwc.com/serbia/individual/other-taxes
https://www2.deloitte.com/content/dam/Deloitte/global/Documents/Tax/dttl-tax-serbiahighlights-2023.pdf

Trading Economics:
![image](https://github.com/Michaela142/social-/assets/129856961/e3093c74-2e6a-48aa-9e54-213333a1b44f)
https://tradingeconomics.com/serbia/indicators

**Comment by LukasBuzogan** [comment]
Corruption Perceptions Index
Od roku 2011 sa meni hodnotenie 
![Screenshot from 2023-07-06 10-24-23](https://github.com/Michaela142/social-/assets/136437413/c7298b2f-ee0c-439d-a021-afbaf880d2bf)
![Screenshot from 2023-07-06 10-24-46](https://github.com/Michaela142/social-/assets/136437413/e23bda6c-6164-438a-9cee-bf7103e21c1b)

**Comment by LukasBuzogan** [comment]
Households - level of internet access
kvoli viacerym types of household pripada k jednemu roku viac notes ale k roznym types of household
Napr.: 2017 - single person - break in time series
           2017 - Single person with dependent children - break in time series, low reliability
